server:
  port: ${PORT:8080}
  tomcat:
    accesslog:
      enabled: false
    basedir: logs

logging:
  file:
    name: logs/${spring.application.name}.log
    max-size: 250MB
    max-history: 30
  level:
    root: info
    com.sgedts.base: debug
  pattern:
    level: "[%X{loggerId}]%5p"

hibernate:
  schema_update:
    unique_constraint_strategy: RECREATE_QUIETLY
spring:
  application:
    name: base
  task:
    scheduling:
      pool:
        size: 10
  profiles:
    active: default
  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB
  datasource:
    url: jdbc:mysql://localhost:3306/base?zeroDateTimeBehavior=CONVERT_TO_NULL&serverTimezone=Asia/Jakarta
    username: root
    password: password
    hikari:
      maximum-pool-size: 5
      max-lifetime: 60000
    tomcat:
      test-while-idle: true
      test-on-borrow: true
      validation-query: SELECT 1
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
        format_sql: true
        schema_update:
          unique_constraint_strategy: RECREATE_QUIETLY
      org:
        hibernate:
          envers:
            audit_table_suffix: _audit
            revision_field_name: revision
            revision_type_field_name: revision_type
    show-sql: false

host:
  ip: localhost
  port: 8080
  path: "base"

cors:
  allowed-origins: "*"
  allowed-methods: "*"
  allowed-headers: "*"
  exposed-headers: "Authorization,Link,X-Total-Count"
  allow-credentials: true
  max-age: 1800

services:
  my-config:
    log-request: 1
    log-response: 1
