#from git
spring:
  jpa:
    show-sql: false
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME:base}?zeroDateTimeBehavior=CONVERT_TO_NULL&serverTimezone=Asia/Jakarta
    username: ${DB_USER}
    password: ${DB_PWD}
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${ENV_SECURITY_CERT}
  kafka:
    bootstrap-servers: ${ENV_KAFKA_SVR}

logging:
  file:
    name: /logs/${spring.application.name}.log
    max-size: 250MB
    max-history: 30
  level:
    root: info
    com.sgedts.base: info

### Application properties goes here
host:
  ip: ${HOST_IP:172.18.185.110}
  port: ${HOST_PORT:32080}
  path: "base"

cors:
  allowed-origins: "*"
  allowed-methods: "*"
  allowed-headers: "*"
  exposed-headers: "Authorization,Link,X-Total-Count"
  allow-credentials: true
  max-age: 1800

swagger:
  host: ${host.ip}:${host.port}
  path: /${host.path}

services: